spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: ecommerce-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: ecommerce-backend
              uri: ${BACKEND_URL:http://localhost:8080}
              predicates:
                - Path=/api/**
          metrics:
            enabled: true
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5500"
                  - "http://127.0.0.1:5500"
                  - "http://localhost:3000"
                  - "http://127.0.0.1:3000"
                  - "http://localhost:5173"
                  - "http://127.0.0.1:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: false
            add-to-simple-url-handler-mapping: true

server:
  port: ${GATEWAY_PORT:8081}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
